services:
              #### Media ####
  jellyfin:
    extends:
      file: ./compose/media/jellyfin.yml
      service: jellyfin
    networks:
      - homeservarr_bridge
    depends_on:
      - traefik

  jellyseerr:
    extends:
      file: ./compose/media/jellyseerr.yml
      service: jellyseerr
    networks:
      - homeservarr_bridge
    depends_on:
      - jellyfin

  prowlarr:
    extends:
      file: ./compose/media/prowlarr.yml
      service: prowlarr
    networks:
      - homeservarr_bridge
    depends_on:
      - jellyfin
        
  radarr:
    extends:
      file: ./compose/media/radarr.yml
      service: radarr
    networks:
      - homeservarr_bridge
    depends_on:
      - prowlarr

  sonarr:
    extends:
      file: ./compose/media/sonarr.yml
      service: sonarr
    networks:
      - homeservarr_bridge
    depends_on:
      - prowlarr

  bazarr:
    extends:
      file: ./compose/media/bazarr.yml
      service: bazarr
    networks:
      - homeservarr_bridge
    depends_on:
      - sonarr
      - radarr
        
  wizarr:
    extends:
      file: ./compose/media/wizarr.yml
      service: wizarr 
    networks:
      - homeservarr_bridge
    depends_on:
      - jellyfin

              #### network ####

  traefik:
    extends:
      file: ./compose/network/traefik.yml
      service: traefik
    networks:
      - homeservarr_bridge

  transmission:
    extends:
      file: ./compose/network/transmission.yml
      service: transmission
    networks:
      - homeservarr_bridge
    depends_on:
      - traefik

  fail2ban:
    extends:
      file: ./compose/network/fail2ban.yml
      service: fail2ban 
    depends_on:
      - traefik

  flaresolverr:
    extends:
      file: ./compose/network/flaresolverr.yml
      service: flaresolverr
    networks:
      - homeservarr_bridge
    depends_on:
      - traefik

              #### tools ####

  vaultwarden:
    extends:
      file: ./compose/tools/vaultwarden.yml
      service: vaultwarden
    networks:
      - homeservarr_bridge
    depends_on:
      - traefik


networks:
  homeservarr_bridge:
    external: true
