services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    group_add:
      - '105'
    volumes:
      - ${SERVER_ROOT}/jellyfin/config:/config
      - ${SERVER_ROOT}/jellyfin/cache:/cache
      - type: bind
        source: ${JELLYFIN_MEDIA_ROOT}
        target: /media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8960:8960
      - 8096:8096
    networks:
      - frontend
      
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    restart: unless-stopped
    volumes:
      - ${SERVER_ROOT}/wizarr/config:/data/database
    ports:
      - 5690:5690
    networks:
      - frontend
      
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
      - TZ=${TZ}
    volumes:
      - ${SERVER_ROOT}/jellyseerr/config:/app/config
    ports:
      - 5055:5055
    networks:
      - frontend
      - backend
      
networks:
  frontend:
    external: true
  backend:
    external: true
