services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    group_add:
      - '105'
    volumes:
      - ${SERVER_ROOT}/jellyfin/config:/config
      - ${SERVER_ROOT}/jellyfin/cache:/cache
      - type: bind
        source: ${JELLYFIN_MEDIA_ROOT}
        target: /media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8960:8960
      - 8096:8096
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
